export const countriesISO = [
  {
    nameKo: '아프가니스탄',
    nameEn: 'Afghanistan',
    code: 'AF',
    flag: '🇦🇫',
  },
  {
    nameKo: '알바니아',
    nameEn: 'Albania',
    code: 'AL',
    flag: '🇦🇱',
  },
  {
    nameKo: '알제리',
    nameEn: 'Algeria',
    code: 'DZ',
    flag: '🇩🇿',
  },
  {
    nameKo: '아메리칸 사모아',
    nameEn: 'American Samoa',
    code: 'AS',
    flag: '🇦🇸',
  },
  {
    nameKo: '안도라',
    nameEn: 'Andorra',
    code: 'AD',
    flag: '🇦🇩',
  },
  {
    nameKo: '앙골라',
    nameEn: 'Angola',
    code: 'AO',
    flag: '🇦🇴',
  },
  {
    nameKo: '앵귈라',
    nameEn: 'Anguilla',
    code: 'AI',
    flag: '🇦🇮',
  },
  {
    nameKo: '남극',
    nameEn: 'Antarctica',
    code: 'AQ',
    flag: '🇦🇶',
  },
  {
    nameKo: '앤티가 바부다',
    nameEn: 'Antigua and Barbuda',
    code: 'AG',
    flag: '🇦🇬',
  },
  {
    nameKo: '아르메니아',
    nameEn: 'Armenia',
    code: 'AM',
    flag: '🇦🇲',
  },
  {
    nameKo: '아루바',
    nameEn: 'Aruba',
    code: 'AW',
    flag: '🇦🇼',
  },
  {
    nameKo: '오스트리아',
    nameEn: 'Austria',
    code: 'AT',
    flag: '🇦🇹',
  },
  {
    nameKo: '아제르바이잔',
    nameEn: 'Azerbaijan',
    code: 'AZ',
    flag: '🇦🇿',
  },
  {
    nameKo: '바하마',
    nameEn: 'Bahamas',
    code: 'BS',
    flag: '🇧🇸',
  },
  {
    nameKo: '바레인',
    nameEn: 'Bahrain',
    code: 'BH',
    flag: '🇧🇭',
  },
  {
    nameKo: '방글라데시',
    nameEn: 'Bangladesh',
    code: 'BD',
    flag: '🇧🇩',
  },
  {
    nameKo: '바베이도스',
    nameEn: 'Barbados',
    code: 'BB',
    flag: '🇧🇧',
  },
  {
    nameKo: '벨라루스',
    nameEn: 'Belarus',
    code: 'BY',
    flag: '🇧🇾',
  },
  {
    nameKo: '벨기에',
    nameEn: 'Belgium',
    code: 'BE',
    flag: '🇧🇪',
  },
  {
    nameKo: '벨리즈',
    nameEn: 'Belize',
    code: 'BZ',
    flag: '🇧🇿',
  },
  {
    nameKo: '베냉',
    nameEn: 'Benin',
    code: 'BJ',
    flag: '🇧🇯',
  },
  {
    nameKo: '버뮤다',
    nameEn: 'Bermuda',
    code: 'BM',
    flag: '🇧🇲',
  },
  {
    nameKo: '부탄',
    nameEn: 'Bhutan',
    code: 'BT',
    flag: '🇧🇹',
  },
  {
    nameKo: '볼리비아',
    nameEn: 'Bolivia, Plurinational State of',
    code: 'BO',
    flag: '🇧🇴',
  },
  {
    nameKo: '보네르 신트외스타티위스 사바',
    nameEn: 'Bonaire, Sint Eustatius and Saba',
    code: 'BQ',
    flag: '🇧🇶',
  },
  {
    nameKo: '보스니아 헤르체고비나',
    nameEn: 'Bosnia and Herzegovina',
    code: 'BA',
    flag: '🇧🇦',
  },
  {
    nameKo: '보츠와나',
    nameEn: 'Botswana',
    code: 'BW',
    flag: '🇧🇼',
  },
  {
    nameKo: '부베 섬',
    nameEn: 'Bouvet Island',
    code: 'BV',
    flag: '🇧🇻',
  },
  {
    nameKo: '영국령 인도양 지역',
    nameEn: 'British Indian Ocean Territory',
    code: 'IO',
    flag: '🇮🇴',
  },
  {
    nameKo: '브루나이',
    nameEn: 'Brunei Darussalam',
    code: 'BN',
    flag: '🇧🇳',
  },
  {
    nameKo: '불가리아',
    nameEn: 'Bulgaria',
    code: 'BG',
    flag: '🇧🇬',
  },
  {
    nameKo: '부르키나파소',
    nameEn: 'Burkina Faso',
    code: 'BF',
    flag: '🇧🇫',
  },
  {
    nameKo: '부룬디',
    nameEn: 'Burundi',
    code: 'BI',
    flag: '🇧🇮',
  },
  {
    nameKo: '카보베르데',
    nameEn: 'Cabo Verde',
    code: 'CV',
    flag: '🇨🇻',
  },
  {
    nameKo: '캄보디아',
    nameEn: 'Cambodia',
    code: 'KH',
    flag: '🇰🇭',
  },
  {
    nameKo: '카메룬',
    nameEn: 'Cameroon',
    code: 'CM',
    flag: '🇨🇲',
  },
  {
    nameKo: '케이맨 제도',
    nameEn: 'Cayman Islands',
    code: 'KY',
    flag: '🇰🇾',
  },
  {
    nameKo: '중앙아프리카공화국',
    nameEn: 'Central African Republic',
    code: 'CF',
    flag: '🇨🇫',
  },
  {
    nameKo: '차드',
    nameEn: 'Chad',
    code: 'TD',
    flag: '🇹🇩',
  },
  {
    nameKo: '칠레',
    nameEn: 'Chile',
    code: 'CL',
    flag: '🇨🇱',
  },
  {
    nameKo: '크리스마스 섬',
    nameEn: 'Christmas Island',
    code: 'CX',
    flag: '🇨🇽',
  },
  {
    nameKo: '코코스 제도',
    nameEn: 'Cocos (Keeling) Islands',
    code: 'CC',
    flag: '🇨🇨',
  },
  {
    nameKo: '콜롬비아',
    nameEn: 'Colombia',
    code: 'CO',
    flag: '🇨🇴',
  },
  {
    nameKo: '코모로',
    nameEn: 'Comoros',
    code: 'KM',
    flag: '🇰🇲',
  },
  {
    nameKo: '콩고',
    nameEn: 'Congo',
    code: 'CG',
    flag: '🇨🇬',
  },
  {
    nameKo: '콩고민주공화국',
    nameEn: 'Congo, The Democratic Republic of the',
    code: 'CD',
    flag: '🇨🇩',
  },
  {
    nameKo: '쿡 제도',
    nameEn: 'Cook Islands',
    code: 'CK',
    flag: '🇨🇰',
  },
  {
    nameKo: '코스타리카',
    nameEn: 'Costa Rica',
    code: 'CR',
    flag: '🇨🇷',
  },
  {
    nameKo: '크로아티아',
    nameEn: 'Croatia',
    code: 'HR',
    flag: '🇭🇷',
  },
  {
    nameKo: '쿠바',
    nameEn: 'Cuba',
    code: 'CU',
    flag: '🇨🇺',
  },
  {
    nameKo: '퀴라소',
    nameEn: 'Curaçao',
    code: 'CW',
    flag: '🇨🇼',
  },
  {
    nameKo: '키프로스',
    nameEn: 'Cyprus',
    code: 'CY',
    flag: '🇨🇾',
  },
  {
    nameKo: '체코',
    nameEn: 'Czechia',
    code: 'CZ',
    flag: '🇨🇿',
  },
  {
    nameKo: '코트디부아르',
    nameEn: "Côte d'Ivoire",
    code: 'CI',
    flag: '🇨🇮',
  },
  {
    nameKo: '지부티',
    nameEn: 'Djibouti',
    code: 'DJ',
    flag: '🇩🇯',
  },
  {
    nameKo: '도미니카',
    nameEn: 'Dominica',
    code: 'DM',
    flag: '🇩🇲',
  },
  {
    nameKo: '도미니카공화국',
    nameEn: 'Dominican Republic',
    code: 'DO',
    flag: '🇩🇴',
  },
  {
    nameKo: '에콰도르',
    nameEn: 'Ecuador',
    code: 'EC',
    flag: '🇪🇨',
  },
  {
    nameKo: '엘살바도르',
    nameEn: 'El Salvador',
    code: 'SV',
    flag: '🇸🇻',
  },
  {
    nameKo: '적도기니',
    nameEn: 'Equatorial Guinea',
    code: 'GQ',
    flag: '🇬🇶',
  },
  {
    nameKo: '에리트레아',
    nameEn: 'Eritrea',
    code: 'ER',
    flag: '🇪🇷',
  },
  {
    nameKo: '에스토니아',
    nameEn: 'Estonia',
    code: 'EE',
    flag: '🇪🇪',
  },
  {
    nameKo: '에스와티니',
    nameEn: 'Eswatini',
    code: 'SZ',
    flag: '🇸🇿',
  },
  {
    nameKo: '에티오피아',
    nameEn: 'Ethiopia',
    code: 'ET',
    flag: '🇪🇹',
  },
  {
    nameKo: '포클랜드 제도',
    nameEn: 'Falkland Islands (Malvinas)',
    code: 'FK',
    flag: '🇫🇰',
  },
  {
    nameKo: '페로 제도',
    nameEn: 'Faroe Islands',
    code: 'FO',
    flag: '🇫🇴',
  },
  {
    nameKo: '피지',
    nameEn: 'Fiji',
    code: 'FJ',
    flag: '🇫🇯',
  },
  {
    nameKo: '프랑스령 기아나',
    nameEn: 'French Guiana',
    code: 'GF',
    flag: '🇬🇫',
  },
  {
    nameKo: '프랑스령 폴리네시아',
    nameEn: 'French Polynesia',
    code: 'PF',
    flag: '🇵🇫',
  },
  {
    nameKo: '프랑스령 남방 및 남극 지역',
    nameEn: 'French Southern Territories',
    code: 'TF',
    flag: '🇹🇫',
  },
  {
    nameKo: '가봉',
    nameEn: 'Gabon',
    code: 'GA',
    flag: '🇬🇦',
  },
  {
    nameKo: '감비아',
    nameEn: 'Gambia',
    code: 'GM',
    flag: '🇬🇲',
  },
  {
    nameKo: '조지아',
    nameEn: 'Georgia',
    code: 'GE',
    flag: '🇬🇪',
  },
  {
    nameKo: '가나',
    nameEn: 'Ghana',
    code: 'GH',
    flag: '🇬🇭',
  },
  {
    nameKo: '지브롤터',
    nameEn: 'Gibraltar',
    code: 'GI',
    flag: '🇬🇮',
  },
  {
    nameKo: '그리스',
    nameEn: 'Greece',
    code: 'GR',
    flag: '🇬🇷',
  },
  {
    nameKo: '그린란드',
    nameEn: 'Greenland',
    code: 'GL',
    flag: '🇬🇱',
  },
  {
    nameKo: '그레나다',
    nameEn: 'Grenada',
    code: 'GD',
    flag: '🇬🇩',
  },
  {
    nameKo: '과들루프',
    nameEn: 'Guadeloupe',
    code: 'GP',
    flag: '🇬🇵',
  },
  {
    nameKo: '괌',
    nameEn: 'Guam',
    code: 'GU',
    flag: '🇬🇺',
  },
  {
    nameKo: '과테말라',
    nameEn: 'Guatemala',
    code: 'GT',
    flag: '🇬🇹',
  },
  {
    nameKo: '건지',
    nameEn: 'Guernsey',
    code: 'GG',
    flag: '🇬🇬',
  },
  {
    nameKo: '기니',
    nameEn: 'Guinea',
    code: 'GN',
    flag: '🇬🇳',
  },
  {
    nameKo: '기니비사우',
    nameEn: 'Guinea-Bissau',
    code: 'GW',
    flag: '🇬🇼',
  },
  {
    nameKo: '가이아나',
    nameEn: 'Guyana',
    code: 'GY',
    flag: '🇬🇾',
  },
  {
    nameKo: '아이티',
    nameEn: 'Haiti',
    code: 'HT',
    flag: '🇭🇹',
  },
  {
    nameKo: '허드 맥도널드 제도',
    nameEn: 'Heard Island and McDonald Islands',
    code: 'HM',
    flag: '🇭🇲',
  },
  {
    nameKo: '바티칸',
    nameEn: 'Holy See (Vatican City State)',
    code: 'VA',
    flag: '🇻🇦',
  },
  {
    nameKo: '온두라스',
    nameEn: 'Honduras',
    code: 'HN',
    flag: '🇭🇳',
  },
  {
    nameKo: '홍콩',
    nameEn: 'Hong Kong',
    code: 'HK',
    flag: '🇭🇰',
  },
  {
    nameKo: '헝가리',
    nameEn: 'Hungary',
    code: 'HU',
    flag: '🇭🇺',
  },
  {
    nameKo: '아이슬란드',
    nameEn: 'Iceland',
    code: 'IS',
    flag: '🇮🇸',
  },
  {
    nameKo: '이란',
    nameEn: 'Iran, Islamic Republic of',
    code: 'IR',
    flag: '🇮🇷',
  },
  {
    nameKo: '이라크',
    nameEn: 'Iraq',
    code: 'IQ',
    flag: '🇮🇶',
  },
  {
    nameKo: '아일랜드',
    nameEn: 'Ireland',
    code: 'IE',
    flag: '🇮🇪',
  },
  {
    nameKo: '맨 섬',
    nameEn: 'Isle of Man',
    code: 'IM',
    flag: '🇮🇲',
  },
  {
    nameKo: '이스라엘',
    nameEn: 'Israel',
    code: 'IL',
    flag: '🇮🇱',
  },
  {
    nameKo: '자메이카',
    nameEn: 'Jamaica',
    code: 'JM',
    flag: '🇯🇲',
  },
  {
    nameKo: '저지',
    nameEn: 'Jersey',
    code: 'JE',
    flag: '🇯🇪',
  },
  {
    nameKo: '요단',
    nameEn: 'Jordan',
    code: 'JO',
    flag: '🇯🇴',
  },
  {
    nameKo: '카자흐스탄',
    nameEn: 'Kazakhstan',
    code: 'KZ',
    flag: '🇰🇿',
  },
  {
    nameKo: '케냐',
    nameEn: 'Kenya',
    code: 'KE',
    flag: '🇰🇪',
  },
  {
    nameKo: '키리바시',
    nameEn: 'Kiribati',
    code: 'KI',
    flag: '🇰🇮',
  },
  {
    nameKo: '북한',
    nameEn: "Korea, Democratic People's Republic of",
    code: 'KP',
    flag: '🇰🇵',
  },
  {
    nameKo: '대한민국',
    nameEn: 'Korea, Republic of',
    code: 'KR',
    flag: '🇰🇷',
  },
  {
    nameKo: '쿠웨이트',
    nameEn: 'Kuwait',
    code: 'KW',
    flag: '🇰🇼',
  },
  {
    nameKo: '키르기스스탄',
    nameEn: 'Kyrgyzstan',
    code: 'KG',
    flag: '🇰🇬',
  },
  {
    nameKo: '라오스',
    nameEn: "Lao People's Democratic Republic",
    code: 'LA',
    flag: '🇱🇦',
  },
  {
    nameKo: '라트비아',
    nameEn: 'Latvia',
    code: 'LV',
    flag: '🇱🇻',
  },
  {
    nameKo: '레바논',
    nameEn: 'Lebanon',
    code: 'LB',
    flag: '🇱🇧',
  },
  {
    nameKo: '레소토',
    nameEn: 'Lesotho',
    code: 'LS',
    flag: '🇱🇸',
  },
  {
    nameKo: '라이베리아',
    nameEn: 'Liberia',
    code: 'LR',
    flag: '🇱🇷',
  },
  {
    nameKo: '리비아',
    nameEn: 'Libya',
    code: 'LY',
    flag: '🇱🇾',
  },
  {
    nameKo: '리히텐슈타인',
    nameEn: 'Liechtenstein',
    code: 'LI',
    flag: '🇱🇮',
  },
  {
    nameKo: '리투아니아',
    nameEn: 'Lithuania',
    code: 'LT',
    flag: '🇱🇹',
  },
  {
    nameKo: '룩셈부르크',
    nameEn: 'Luxembourg',
    code: 'LU',
    flag: '🇱🇺',
  },
  {
    nameKo: '마카오',
    nameEn: 'Macao',
    code: 'MO',
    flag: '🇲🇴',
  },
  {
    nameKo: '마다가스카르',
    nameEn: 'Madagascar',
    code: 'MG',
    flag: '🇲🇬',
  },
  {
    nameKo: '말라위',
    nameEn: 'Malawi',
    code: 'MW',
    flag: '🇲🇼',
  },
  {
    nameKo: '몰디브',
    nameEn: 'Maldives',
    code: 'MV',
    flag: '🇲🇻',
  },
  {
    nameKo: '말리',
    nameEn: 'Mali',
    code: 'ML',
    flag: '🇲🇱',
  },
  {
    nameKo: '몰타',
    nameEn: 'Malta',
    code: 'MT',
    flag: '🇲🇹',
  },
  {
    nameKo: '마셜 제도',
    nameEn: 'Marshall Islands',
    code: 'MH',
    flag: '🇲🇭',
  },
  {
    nameKo: '마르티니크',
    nameEn: 'Martinique',
    code: 'MQ',
    flag: '🇲🇶',
  },
  {
    nameKo: '모리타니',
    nameEn: 'Mauritania',
    code: 'MR',
    flag: '🇲🇷',
  },
  {
    nameKo: '모리셔스',
    nameEn: 'Mauritius',
    code: 'MU',
    flag: '🇲🇺',
  },
  {
    nameKo: '마요트',
    nameEn: 'Mayotte',
    code: 'YT',
    flag: '🇾🇹',
  },
  {
    nameKo: '미크로네시아',
    nameEn: 'Micronesia, Federated States of',
    code: 'FM',
    flag: '🇫🇲',
  },
  {
    nameKo: '몰도바',
    nameEn: 'Moldova, Republic of',
    code: 'MD',
    flag: '🇲🇩',
  },
  {
    nameKo: '모나코',
    nameEn: 'Monaco',
    code: 'MC',
    flag: '🇲🇨',
  },
  {
    nameKo: '몽골',
    nameEn: 'Mongolia',
    code: 'MN',
    flag: '🇲🇳',
  },
  {
    nameKo: '몬테네그로',
    nameEn: 'Montenegro',
    code: 'ME',
    flag: '🇲🇪',
  },
  {
    nameKo: '몬트세랫',
    nameEn: 'Montserrat',
    code: 'MS',
    flag: '🇲🇸',
  },
  {
    nameKo: '모로코',
    nameEn: 'Morocco',
    code: 'MA',
    flag: '🇲🇦',
  },
  {
    nameKo: '모잠비크',
    nameEn: 'Mozambique',
    code: 'MZ',
    flag: '🇲🇿',
  },
  {
    nameKo: '미얀마',
    nameEn: 'Myanmar',
    code: 'MM',
    flag: '🇲🇲',
  },
  {
    nameKo: '나미비아',
    nameEn: 'Namibia',
    code: 'NA',
    flag: '🇳🇦',
  },
  {
    nameKo: '나우루',
    nameEn: 'Nauru',
    code: 'NR',
    flag: '🇳🇷',
  },
  {
    nameKo: '네팔',
    nameEn: 'Nepal',
    code: 'NP',
    flag: '🇳🇵',
  },
  {
    nameKo: '네덜란드',
    nameEn: 'Netherlands',
    code: 'NL',
    flag: '🇳🇱',
  },
  {
    nameKo: '뉴칼레도니아',
    nameEn: 'New Caledonia',
    code: 'NC',
    flag: '🇳🇨',
  },
  {
    nameKo: '뉴질랜드',
    nameEn: 'New Zealand',
    code: 'NZ',
    flag: '🇳🇿',
  },
  {
    nameKo: '니카라과',
    nameEn: 'Nicaragua',
    code: 'NI',
    flag: '🇳🇮',
  },
  {
    nameKo: '니제르',
    nameEn: 'Niger',
    code: 'NE',
    flag: '🇳🇪',
  },
  {
    nameKo: '나이지리아',
    nameEn: 'Nigeria',
    code: 'NG',
    flag: '🇳🇬',
  },
  {
    nameKo: '니우에',
    nameEn: 'Niue',
    code: 'NU',
    flag: '🇳🇺',
  },
  {
    nameKo: '노퍽 섬',
    nameEn: 'Norfolk Island',
    code: 'NF',
    flag: '🇳🇫',
  },
  {
    nameKo: '북마케도니아',
    nameEn: 'North Macedonia',
    code: 'MK',
    flag: '🇲🇰',
  },
  {
    nameKo: '북마리아나 제도',
    nameEn: 'Northern Mariana Islands',
    code: 'MP',
    flag: '🇲🇵',
  },
  {
    nameKo: '오만',
    nameEn: 'Oman',
    code: 'OM',
    flag: '🇴🇲',
  },
  {
    nameKo: '파키스탄',
    nameEn: 'Pakistan',
    code: 'PK',
    flag: '🇵🇰',
  },
  {
    nameKo: '팔라우',
    nameEn: 'Palau',
    code: 'PW',
    flag: '🇵🇼',
  },
  {
    nameKo: '팔레스타인',
    nameEn: 'Palestine, State of',
    code: 'PS',
    flag: '🇵🇸',
  },
  {
    nameKo: '파나마',
    nameEn: 'Panama',
    code: 'PA',
    flag: '🇵🇦',
  },
  {
    nameKo: '파푸아뉴기니',
    nameEn: 'Papua New Guinea',
    code: 'PG',
    flag: '🇵🇬',
  },
  {
    nameKo: '파라과이',
    nameEn: 'Paraguay',
    code: 'PY',
    flag: '🇵🇾',
  },
  {
    nameKo: '페루',
    nameEn: 'Peru',
    code: 'PE',
    flag: '🇵🇪',
  },
  {
    nameKo: '핏케언 제도',
    nameEn: 'Pitcairn',
    code: 'PN',
    flag: '🇵🇳',
  },
  {
    nameKo: '폴란드',
    nameEn: 'Poland',
    code: 'PL',
    flag: '🇵🇱',
  },
  {
    nameKo: '포르투갈',
    nameEn: 'Portugal',
    code: 'PT',
    flag: '🇵🇹',
  },
  {
    nameKo: '푸에르토리코',
    nameEn: 'Puerto Rico',
    code: 'PR',
    flag: '🇵🇷',
  },
  {
    nameKo: '카타르',
    nameEn: 'Qatar',
    code: 'QA',
    flag: '🇶🇦',
  },
  {
    nameKo: '루마니아',
    nameEn: 'Romania',
    code: 'RO',
    flag: '🇷🇴',
  },
  {
    nameKo: '러시아',
    nameEn: 'Russian Federation',
    code: 'RU',
    flag: '🇷🇺',
  },
  {
    nameKo: '르완다',
    nameEn: 'Rwanda',
    code: 'RW',
    flag: '🇷🇼',
  },
  {
    nameKo: '레위니옹',
    nameEn: 'Réunion',
    code: 'RE',
    flag: '🇷🇪',
  },
  {
    nameKo: '생바르텔레미',
    nameEn: 'Saint Barthélemy',
    code: 'BL',
    flag: '🇧🇱',
  },
  {
    nameKo: '세인트헬레나',
    nameEn: 'Saint Helena, Ascension and Tristan da Cunha',
    code: 'SH',
    flag: '🇸🇭',
  },
  {
    nameKo: '세인트키츠 네비스',
    nameEn: 'Saint Kitts and Nevis',
    code: 'KN',
    flag: '🇰🇳',
  },
  {
    nameKo: '세인트루시아',
    nameEn: 'Saint Lucia',
    code: 'LC',
    flag: '🇱🇨',
  },
  {
    nameKo: '생마르탱',
    nameEn: 'Saint Martin (French part)',
    code: 'MF',
    flag: '🇲🇫',
  },
  {
    nameKo: '생피에르 미클롱',
    nameEn: 'Saint Pierre and Miquelon',
    code: 'PM',
    flag: '🇵🇲',
  },
  {
    nameKo: '세인트빈센트 그레나딘',
    nameEn: 'Saint Vincent and the Grenadines',
    code: 'VC',
    flag: '🇻🇨',
  },
  {
    nameKo: '사모아',
    nameEn: 'Samoa',
    code: 'WS',
    flag: '🇼🇸',
  },
  {
    nameKo: '산마리노',
    nameEn: 'San Marino',
    code: 'SM',
    flag: '🇸🇲',
  },
  {
    nameKo: '상투메 프린시페',
    nameEn: 'Sao Tome and Principe',
    code: 'ST',
    flag: '🇸🇹',
  },
  {
    nameKo: '세네갈',
    nameEn: 'Senegal',
    code: 'SN',
    flag: '🇸🇳',
  },
  {
    nameKo: '세르비아',
    nameEn: 'Serbia',
    code: 'RS',
    flag: '🇷🇸',
  },
  {
    nameKo: '세이셸',
    nameEn: 'Seychelles',
    code: 'SC',
    flag: '🇸🇨',
  },
  {
    nameKo: '시에라리온',
    nameEn: 'Sierra Leone',
    code: 'SL',
    flag: '🇸🇱',
  },
  {
    nameKo: '신트마르턴',
    nameEn: 'Sint Maarten (Dutch part)',
    code: 'SX',
    flag: '🇸🇽',
  },
  {
    nameKo: '슬로바키아',
    nameEn: 'Slovakia',
    code: 'SK',
    flag: '🇸🇰',
  },
  {
    nameKo: '슬로베니아',
    nameEn: 'Slovenia',
    code: 'SI',
    flag: '🇸🇮',
  },
  {
    nameKo: '솔로몬 제도',
    nameEn: 'Solomon Islands',
    code: 'SB',
    flag: '🇸🇧',
  },
  {
    nameKo: '소말리아',
    nameEn: 'Somalia',
    code: 'SO',
    flag: '🇸🇴',
  },
  {
    nameKo: '사우스조지아 사우스샌드위치 제도',
    nameEn: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    flag: '🇬🇸',
  },
  {
    nameKo: '남수단',
    nameEn: 'South Sudan',
    code: 'SS',
    flag: '🇸🇸',
  },
  {
    nameKo: '스리랑카',
    nameEn: 'Sri Lanka',
    code: 'LK',
    flag: '🇱🇰',
  },
  {
    nameKo: '수단',
    nameEn: 'Sudan',
    code: 'SD',
    flag: '🇸🇩',
  },
  {
    nameKo: '수리남',
    nameEn: 'Suriname',
    code: 'SR',
    flag: '🇸🇷',
  },
  {
    nameKo: '스발바르 얀마옌',
    nameEn: 'Svalbard and Jan Mayen',
    code: 'SJ',
    flag: '🇸🇯',
  },
  {
    nameKo: '스위스',
    nameEn: 'Switzerland',
    code: 'CH',
    flag: '🇨🇭',
  },
  {
    nameKo: '시리아',
    nameEn: 'Syrian Arab Republic',
    code: 'SY',
    flag: '🇸🇾',
  },
  {
    nameKo: '대만',
    nameEn: 'Taiwan, Province of China',
    code: 'TW',
    flag: '🇹🇼',
  },
  {
    nameKo: '타지키스탄',
    nameEn: 'Tajikistan',
    code: 'TJ',
    flag: '🇹🇯',
  },
  {
    nameKo: '탄자니아',
    nameEn: 'Tanzania, United Republic of',
    code: 'TZ',
    flag: '🇹🇿',
  },
  {
    nameKo: '동티모르',
    nameEn: 'Timor-Leste',
    code: 'TL',
    flag: '🇹🇱',
  },
  {
    nameKo: '토고',
    nameEn: 'Togo',
    code: 'TG',
    flag: '🇹🇬',
  },
  {
    nameKo: '토켈라우',
    nameEn: 'Tokelau',
    code: 'TK',
    flag: '🇹🇰',
  },
  {
    nameKo: '통가',
    nameEn: 'Tonga',
    code: 'TO',
    flag: '🇹🇴',
  },
  {
    nameKo: '트리니다드 토바고',
    nameEn: 'Trinidad and Tobago',
    code: 'TT',
    flag: '🇹🇹',
  },
  {
    nameKo: '튀니지',
    nameEn: 'Tunisia',
    code: 'TN',
    flag: '🇹🇳',
  },
  {
    nameKo: '투르크메니스탄',
    nameEn: 'Turkmenistan',
    code: 'TM',
    flag: '🇹🇲',
  },
  {
    nameKo: '터크스 케이코스 제도',
    nameEn: 'Turks and Caicos Islands',
    code: 'TC',
    flag: '🇹🇨',
  },
  {
    nameKo: '투발루',
    nameEn: 'Tuvalu',
    code: 'TV',
    flag: '🇹🇻',
  },
  {
    nameKo: '우간다',
    nameEn: 'Uganda',
    code: 'UG',
    flag: '🇺🇬',
  },
  {
    nameKo: '우크라이나',
    nameEn: 'Ukraine',
    code: 'UA',
    flag: '🇺🇦',
  },
  {
    nameKo: '아랍에미리트',
    nameEn: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
  },
  {
    nameKo: '미국령 군소 제도',
    nameEn: 'United States Minor Outlying Islands',
    code: 'UM',
    flag: '🇺🇲',
  },
  {
    nameKo: '우루과이',
    nameEn: 'Uruguay',
    code: 'UY',
    flag: '🇺🇾',
  },
  {
    nameKo: '우즈베키스탄',
    nameEn: 'Uzbekistan',
    code: 'UZ',
    flag: '🇺🇿',
  },
  {
    nameKo: '바누아투',
    nameEn: 'Vanuatu',
    code: 'VU',
    flag: '🇻🇺',
  },
  {
    nameKo: '베네수엘라',
    nameEn: 'Venezuela, Bolivarian Republic of',
    code: 'VE',
    flag: '🇻🇪',
  },
  {
    nameKo: '베트남',
    nameEn: 'Viet Nam',
    code: 'VN',
    flag: '🇻🇳',
  },
  {
    nameKo: '영국령 버진아일랜드',
    nameEn: 'Virgin Islands, British',
    code: 'VG',
    flag: '🇻🇬',
  },
  {
    nameKo: '미국령 버진아일랜드',
    nameEn: 'Virgin Islands, U.S.',
    code: 'VI',
    flag: '🇻🇮',
  },
  {
    nameKo: '왈리스 퓌튀나',
    nameEn: 'Wallis and Futuna',
    code: 'WF',
    flag: '🇼🇫',
  },
  {
    nameKo: '서사하라',
    nameEn: 'Western Sahara',
    code: 'EH',
    flag: '🇪🇭',
  },
  {
    nameKo: '예멘',
    nameEn: 'Yemen',
    code: 'YE',
    flag: '🇾🇪',
  },
  {
    nameKo: '잠비아',
    nameEn: 'Zambia',
    code: 'ZM',
    flag: '🇿🇲',
  },
  {
    nameKo: '짐바브웨',
    nameEn: 'Zimbabwe',
    code: 'ZW',
    flag: '🇿🇼',
  },
  {
    nameKo: '올란드 제도',
    nameEn: 'Åland Islands',
    code: 'AX',
    flag: '🇦🇽',
  },
  {
    nameKo: '남아프리카 공화국',
    nameEn: 'South Africa',
    code: 'ZA',
    flag: '🇿🇦',
  },
  {
    nameKo: '노르웨이',
    nameEn: 'Norway',
    code: 'NO',
    flag: '🇳🇴',
  },
  {
    nameKo: '덴마크',
    nameEn: 'Denmark',
    code: 'DK',
    flag: '🇩🇰',
  },
  {
    nameKo: '독일',
    nameEn: 'Germany',
    code: 'DE',
    flag: '🇩🇪',
  },
  {
    nameKo: '말레이시아',
    nameEn: 'Malaysia',
    code: 'MY',
    flag: '🇲🇾',
  },
  {
    nameKo: '멕시코',
    nameEn: 'Mexico',
    code: 'MX',
    flag: '🇲🇽',
  },
  {
    nameKo: '미국',
    nameEn: 'United States',
    code: 'US',
    flag: '🇺🇸',
  },
  {
    nameKo: '브라질',
    nameEn: 'Brazil',
    code: 'BR',
    flag: '🇧🇷',
  },
  {
    nameKo: '사우디아라비아',
    nameEn: 'Saudi Arabia',
    code: 'SA',
    flag: '🇸🇦',
  },
  {
    nameKo: '스웨덴',
    nameEn: 'Sweden',
    code: 'SE',
    flag: '🇸🇪',
  },
  {
    nameKo: '스페인',
    nameEn: 'Spain',
    code: 'ES',
    flag: '🇪🇸',
  },
  {
    nameKo: '싱가포르',
    nameEn: 'Singapore',
    code: 'SG',
    flag: '🇸🇬',
  },
  {
    nameKo: '아르헨티나',
    nameEn: 'Argentina',
    code: 'AR',
    flag: '🇦🇷',
  },
  {
    nameKo: '영국',
    nameEn: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
  },
  {
    nameKo: '이집트',
    nameEn: 'Egypt',
    code: 'EG',
    flag: '🇪🇬',
  },
  {
    nameKo: '이탈리아',
    nameEn: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
  },
  {
    nameKo: '인도',
    nameEn: 'India',
    code: 'IN',
    flag: '🇮🇳',
  },
  {
    nameKo: '인도네시아',
    nameEn: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
  },
  {
    nameKo: '일본',
    nameEn: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
  },
  {
    nameKo: '중국',
    nameEn: 'China',
    code: 'CN',
    flag: '🇨🇳',
  },
  {
    nameKo: '캐나다',
    nameEn: 'Canada',
    code: 'CA',
    flag: '🇨🇦',
  },
  {
    nameKo: '태국',
    nameEn: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
  },
  {
    nameKo: '튀르키예',
    nameEn: 'Turkey',
    code: 'TR',
    flag: '🇹🇷',
  },
  {
    nameKo: '프랑스',
    nameEn: 'France',
    code: 'FR',
    flag: '🇫🇷',
  },
  {
    nameKo: '핀란드',
    nameEn: 'Finland',
    code: 'FI',
    flag: '🇫🇮',
  },
  {
    nameKo: '필리핀',
    nameEn: 'Philippines',
    code: 'PH',
    flag: '🇵🇭',
  },
  {
    nameKo: '호주',
    nameEn: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
  },
];
